esphome:
  name: dummy_scanner

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: ./components
    components: [ m5stack_barcode ]

event:
  - id: my_barcode_event
    # Optional: Add event type if needed by your component's logic, e.g.
    # event_type: scan_successful 

# Minimal configuration for the component
m5stack_barcode:
  id: my_scanner
  barcode_event: my_barcode_event # Link to the event defined above

uart:
  id: uart_bus
  tx_pin: 1
  rx_pin: 3
  baud_rate: 115200
